version: "3"

tasks:
    protoc-go-gen:
        desc: "Generate .go files from .proto files"
        cmds:
            - rm -rf ./pkg/client/*
            - protoc -I ./api ./api/submission.proto --go_out=./pkg/client --validate_out="lang=go,paths=source_relative:./pkg/client" --go_opt=paths=source_relative --go-grpc_out=./pkg/client --go-grpc_opt=paths=source_relative
    run-local:
        desc: "Run service on a local machine"
        cmds:
            - go run ./cmd/main.go --config ./config/local.yml
    test:
        desc: "Run all rests"
        cmds:
            - go clean -testcache
            - gotestsum --format-hide-empty-pkg --format-icons hivis -- -coverprofile=cover.out ./...
    mockgen:
        desc: "Generate all mocks"
        cmds:
            - rm -rf internal/util/mocks/*
            - mockgen -source=internal/repository/submission/repository.go -destination=internal/util/mocks/mock_submission_repository.go -package mocks -mock_names Repository=SubmissionRepository Repository
            - mockgen -source=internal/service/submission/service.go -destination=internal/util/mocks/mock_submission_service.go -package mocks -mock_names Service=SubmissionService Service
            - mockgen -source=internal/middleware/common/auth/auth.go -destination=internal/util/mocks/mock_auth_client_middleware.go -package mocks -mock_names Client=AuthClientMW Client
